### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Jason-WT**
Add a new survey of zero-shot learning

### CODE REVIEW

**Comment by chichilicious** [comment]
@Jason-WT could you please add it under other papers and follow the exact format. Thank you!

**Comment by Jason-WT** [comment]
> @Jason-WT could you please add it under other papers and follow the exact format. Thank you!
I'm sorry. But the paper I added is not a conference paper, which is a journal paper. The no other papers from the journal. And the format I added is the same as the format you give in the file.

**Comment by chichilicious** [comment]
> > @Jason-WT could you please add it under other papers and follow the exact format. Thank you!
> > I'm sorry. But the paper I added is not a conference paper, which is a journal paper. The no other papers from the journal. And the format I added is the same as the format you give in the file.



The full form of the journal name is not required. It's alright, you can add it under 'other papers' now.

**Comment by Jason-WT** [comment]
> > > @Jason-WT could you please add it under other papers and follow the exact format. Thank you!
> > > I'm sorry. But the paper I added is not a conference paper, which is a journal paper. The no other papers from the journal. And the format I added is the same as the format you give in the file.
> 
> The full form of the journal name is not required. It's alright, you can add it under 'other papers' now.

Thank you! I add it to the other papers, and delete the full form of the journal name. I'm the first time to commit.

**Pull request merged**
